name: Cleanup
on:
  delete

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "${{ github.ref_name }}"

      - name: Test
        run: echo "${{ github.event.ref }}"

      - name: Dump event payload
        run: echo '${{toJSON(github.event)}}'

