name: Cleanup
on:
  delete

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "${{ github.event.ref }}"
      - name: Cleanup GitHub Assets
        run: gh release delete "${{ github.event.ref }}-latest" --cleanup-tag --yes
